p = {0, 1} -> positive(1) or negative(0) feedback

from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()
tfidfed = vectorizer.fit_transform(review_summaries)

print tfidfed[0]
print type(tfidfed)
print tfidfed.shape
#print vectorizer.get_feature_names()

(0, 9000)	0.7826006712289116
(0, 2641)	0.6225240472399899
<class 'scipy.sparse.csr.csr_matrix'>
(110163, 16230)
здесь tfidfed - матрица размером (110163, 16230) где 
колличество строк это колличество документов(читай отзывов),
кол-во ст-ов это кол-во уникальных слов во всем корпусе 
документов. Т.е в матрице выше строки это отзывы 
представленные в виде "разложенния" на вектора уникальных
слов в весами tfidf.

In [31]:
import numpy as np
a = np.array([[1, 2], [3, 4]])
np.random.choice(10)


6

In [40]:
import math
print(1/(1+math.exp(-0.5)))

0.622459331202


In [46]:
import numpy as np
a = np.array(range(3))
#print(a)
b = np.vstack((a, np.array([4, 5, 6])))
print(b)
print(a)
print(b.shape)
b[1] = None
print(b)

[[0 1 2]
 [4 5 6]]
[0 1 2]
(2, 3)


TypeError: long() argument must be a string or a number, not 'NoneType'

In [16]:
import numpy as np
y_proba = np.array([[0.4, .6], [0.3, 0.7], [0.5, 0.5], [0.6, 0.4]])
print([int(i[1] // 0.5) for i in y_proba])
y_pred = np.array([int(i[1] // 0.5) for i in y_proba])
print(y_pred)

[1, 1, 1, 0]
[1 1 1 0]


In [31]:
import numpy as np
from scipy import sparse

def sigmoid(x):
    return 1/(1+np.exp(-x))
a = sparse.csr.csr_matrix([[1, 1, 1], [2, 2, 2]]) 
b = np.array([2, 2, 2])
print(a)
print(b)
print(a * b)
sigmoid(a * b)


  (0, 0)	1
  (0, 1)	1
  (0, 2)	1
  (1, 0)	2
  (1, 1)	2
  (1, 2)	2
[2 2 2]
[ 6 12]


array([0.99752738, 0.99999386])

In [10]:
import numpy as np
a = np.array([[0.9, 0.6], [.1, .5]])
print(a)
a.argmax(axis=1)

[[0.9 0.6]
 [0.1 0.5]]


array([0, 1])

In [2]:
np.sigmoid

NameError: name 'np' is not defined