In [1]:
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6]])
#print a
#print a.shape
m = np.array(range(10))
#print m, m.shape
e = np.eye(10, M=4, k=2)
#print e, e.shape
z = np.zeros((3, 3, 3))
#print z
o = np.ones((3, 3, 3))
#print o
f = np.full((3, 3, 3), 4.78)
#print f
b = np.array([[1, 2, 3], [4, 5, 6]])
#print b, b.shape
c = b.flatten()
#print c
bt = b.T
#print bt
rs = b.reshape((3, 2))
print rs
import random
w = np.array(random.sample(range(1000), 12))
w = w.reshape((2, 2, 3))
print w
print '\n'
#print w.transpose(0, 2, 1)
'''print w.min()
print w.max(axis=0) 
print w.mean(axis=1)
print w.std(axis=2)
print w.mean(axis=None)
print w.sum(axis=1)
print w.prod(axis=2)
print w.cumsum(axis=0)
print w.cumprod(axis=1)'''
a.dot(b)
np.linalg.matrix_power(M, n)
np.linalg.norm(a, ord=None)
np.linalg.inv(a)

SyntaxError: Missing parentheses in call to 'print'. Did you mean print(rs)? (<ipython-input-1-78f8947dd8ae>, line 22)

In [76]:
mat = np.eye(3, M=4) + np.eye(3, M=4) + np.eye(3, M=4, k=1)
#print mat
f = mat.flatten()
a = f.reshape((12, 1))
#print a

In [2]:
import numpy as np 

x_shape = tuple(map(int, input().split()))
X = np.fromiter(map(int, input().split()), np.int).reshape(x_shape)
y_shape = tuple(map(int, input().split()))
Y = np.fromiter(map(int, input().split()), np.int).reshape(y_shape)
Y = Y.T
try:
    print(X.dot(Y))
except ValueError:
    print('matrix shapes do not match')

2 3 
1 2 3 4 5 6 
4 3
1 2 3 4 5 6  7 8 9 0 11 12
[[ 14  32  50  58]
 [ 32  77 122 127]]


In [13]:


x_shape = tuple(map(int, input().split()))
X = np.fromiter(map(int, input().split()), np.int).reshape(x_shape)
y_shape = tuple(map(int, input().split()))
Y = np.fromiter(map(int, input().split()), np.int).reshape(y_shape)
Y = Y.T
X.dot(Y)

1
1
1
1


1

In [ ]:
from urllib.request import urlopen
import numpy as np

filename = input()
f = urlopen(filename)

data = np.loadtxt(f, skiprows=1, delimiter=',')
type(data)
ans = data.mean(axis=0)
print(ans)

In [31]:
import numpy as np
x = np.array(([3, 185], [185, 11725]))
#print(x)
x = np.matrix(([3, 185], [185, 11725]))
x1 = x.I
r = np.matrix([[29], [1850]])
b = x1 * r
print(b)

[[-2.34210526]
 [ 0.19473684]]


In [62]:
import numpy as np
with open('/home/vasya/Downloads/boston_houses.csv', 'r') as f:
    data = np.loadtxt(f, delimiter=',', skiprows=1)
#print(type(data))
Y = data[:, 0][:, np.newaxis]
#print(data)
#print(data.shape)
data = data[:, 1:]
ones = np.ones(data.shape[0])[:, np.newaxis]
#print(ones.shape, ones)
X  = np.hstack((ones, data))
#print(X)
first = np.matrix(X.T.dot(X)).I
first = np.array(first)
#print(first.shape, X.T.shape, Y.shape)
b = (first.dot(X.T)).dot(Y)

#print(b.shape)
#print(type(b))
b = b.flatten()
#print(b)
ans  = ' '.join(map(str, b))
print(ans)
#print(type(ans))
n = np.array(range(10))
#print(' '.join(map(str, n)))

-3.655804285058417 -0.2163955023691392 0.07373059817548971 4.412450576912836 -25.46844878410251 7.143201550745909 -1.3010876776491929
