In [1]:
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)
print(a.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [13]:
print(np.eye(5,3, k=-1))
print(np.array([[1, 2, 3], [4, 5, 6]]))
print(np.zeros((6, 7)))
print(np.ones((2, 3)))
print(np.full((2, 4), 16))

[[0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]
[[1 2 3]
 [4 5 6]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[16 16 16 16]
 [16 16 16 16]]


In [16]:
print(a)
print(a[1, 1], a[0, 2])
print(a[..., 2], a[:, 2])

[[1 2 3]
 [4 5 6]]
5 3
[3 6] [3 6]


In [3]:
b = np.eye(3, 4) * 2 + np.eye(3, 4, k = 1)
print(b)

[[2. 1. 0. 0.]
 [0. 2. 1. 0.]
 [0. 0. 2. 1.]]


In [4]:
import random
w = np.array(random.sample(range(1000), 12)) # одномерный массив из 12 случайных чисел от 1 до 1000
w = w.reshape((2,2,3)) # превратим w в трёхмерную матрицу
print(w)
print()
print(w.transpose(0,2,1))
print()
print(w.flatten())

[[[121 186 322]
  [127 925 813]]

 [[506 922 159]
  [683 539 525]]]

[[[121 127]
  [186 925]
  [322 813]]

 [[506 683]
  [922 539]
  [159 525]]]

[121 186 322 127 925 813 506 922 159 683 539 525]


In [9]:
v = np.array([[1, 2, 3, 4],
 [1, 2, 3, 4],
 [1, 2, 3, 4]])
print(v)

print(v.mean(axis=0))  # вдоль столбцов

print(v.mean(axis=1))  # вдоль строк

print(v.mean(axis=None))  # вдоль всего массива

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]
[1. 2. 3. 4.]
[2.5 2.5 2.5]
2.5


a.dot(b) — матричное произведение двух массивов (размерности должны быть согласованы),

linalg.matrix_power(M, n) — возведение матрицы M в степень n,

a.T — транспонирование

linalg.norm(a, ord=None) — норма матрицы a, по умолчанию норма Фробениуса для матриц и L2-норма для
векторов 

linalg.inv(a) — матрица, обратная к a (если a необратима, выбрасывается LinAlgError псевдообратная считается чере linalg.pinv(a))
    
a.sum(axis=None), a.prod(axis=None) — сумма и произведение всех элементов вдоль указанной оси. 

a.cumsum(axis=None), a.cumprod(axis=None) — частичные суммы и произведения (для (a1,⋯,an) вектор частичных сумм — 
                                                                            это (a1,a1+a2,⋯,a1+⋯+an))
                                                                            
a.min(axis=None), a.max(axis=None), a.mean(axis=None), a.std(axis=None) — минимум, максимум, среднее арифметическое 
и стандартное отклонение вдоль указанной оси. По умолчанию ось не указана и статистика считается по всему массиву. 

a.argmin(axis=None), a.argmax(axis=None) — индексы минимального и максимального элемента. 

sbux = np.loadtxt("sbux.csv", usecols=(0,1,4), skiprows=1, delimiter=",", dtype={'names': ('date', 'open', 'close'),
                             'formats': ('datetime64[D]', 'f4', 'f4')})

np.hstack((array1, array2, ...))  # склеивает по строкам массивы, являющиеся компонентами кортежа, поданного на вход; 
массивы должны совпадать по всем измерениям, кроме второго

np.ones_like(array)  # создаёт массив, состоящий из единиц, идентичный по форме массиву array

In [4]:
print(np.newaxis)

None
